### ISSUE TITLE
No such module RyuCrypto

### ISSUE THREAD

**Issue by lrmz** [Ryucoin/neovm-utils#11]
When I added the files in the neoutils.framework and Classes folders, Crypto.swift prompts No such module RyuCrypto at compile time.

**Comment by WyattMufson** [comment]
You need to follow the install instructions. Install it as-well as its dependencies. `RyuCrypto` is one of the dependencies and is also available via Cocoa Pods.

You should add `neovmUtils` to your `Podfile` and install with the `pod install` command.

**Comment by WyattMufson** [comment]
@lrmz how are you installing it? You should not just be dragging the `neoutils.framework` and the classes folder. You should be using the pod. Otherwise you won't get the `RyuCrypto` dependency (https://github.com/Ryucoin/trezor-crypto-ios).

**Comment by lrmz** [comment]
When I use pod search neovmUtils in the command line tool, I am prompted to Unable to find a pod with name, author, summary, or description matching `neovmUtils`

**Comment by WyattMufson** [comment]
Did you add `neovmUtils` to your Podfile and run `pod install`?

**Comment by lrmz** [comment]
Yes

**Comment by WyattMufson** [comment]
And what happens when you do that? What prints in terminal?

**Comment by lrmz** [comment]
Unable to find a specification for `neovmUtils`

**Comment by WyattMufson** [comment]
What does your Podfile look like?

**Comment by lrmz** [comment]
platform :ios, '9.0'

target 'neovmUtilsTest' do
  use_frameworks!

  pod 'neovmUtils'

end

**Comment by WyattMufson** [comment]
- `neovmUtils` requires iOS 12 or higher
- Try running `repo update master`

**Comment by lrmz** [comment]
platform :ios, '12.1'

target 'neovmUtilsTest' do
 use_frameworks!
  
 pod 'neovmUtils'

end

**Comment by lrmz** [comment]
Unable to find a specification for `neovmUtils`

**Comment by WyattMufson** [comment]
Are you using the most recent version of Cocoa Pods and have you run ‘pod update’?

The travis ci tests are passing and it’s definitely available on Cocoa Pods.
