### ISSUE TITLE
Missing password

### ISSUE THREAD

**Issue by lrmz** [Ryucoin/neovm-utils#14]
When I was using neovmUtils, I found that I don't need to pass the password when creating a new wallet, and there is no way to verify that the password is correct.

**Comment by WyattMufson** [comment]
I don’t understand your issue. Passwords aren’t required for wallet creation.

You can create a wallet from an encrypted key/passphrase combination or you can create a new pair from an existing wallet.

What is the specific issue you are having?

**Comment by WyattMufson** [comment]
Take a look at the wallet documentation: https://github.com/Ryucoin/neovm-utils/blob/master/docs/wallet.md

**Comment by lrmz** [comment]
The creation of a wallet in ontology requires a password. If there is no password, and when operating the related functions of the wallet, the assets in my wallet are easily stolen.

**Comment by WyattMufson** [comment]
Are you talking about a private key?

**Comment by WyattMufson** [comment]
`newWallet()` creates a `Wallet` class. This works for both NEO and Ontology wallets. It's like this [function from the Ontology TS SDK](https://github.com/ontio/ontology-ts-sdk/blob/master/src/wallet.ts#L67).

When you create a `Wallet` it creates all of the fields on the wallet automatically. I'd recommend reading the documentation some more.

**Comment by lrmz** [comment]
You can refer to this document  https://ontio.github.io/documentation/ontology_ts_sdk_asset_en.html

**Comment by WyattMufson** [comment]
Which specifically about that are you referring to? You linked to documentation that mirrors what I just posted:
```
import {Wallet} from 'ontology-ts-sdk';
var wallet = Wallet.create('my_wallet')
```

That string is a label, not a password. Ontology wallets do not in-fact require a password.

You can [read the documentation](https://github.com/Ryucoin/neovm-utils/blob/master/docs/wallet.md#new-encryptedkey) about how to create an encrypted key with a password using ECDSA encryption.

**Comment by lrmz** [comment]
You just created a wallet file, you must add an account to this wallet, this wallet can be used normally, such as transfer

**Comment by WyattMufson** [comment]
That is correct. This is a hybrid NEO/Ontology wallet - it's a simplified wallet with just one account. You can check out the [TS Wallet specification](https://github.com/ontio/ontology-ts-sdk/blob/master/docs/en/Wallet_File_Specification.md). You may notice that password is not included in the specification (the word "password" is not included on the page).

The account is not specified to be some required feature of an Ontology wallet - it just happens to be a feature of the TS sdk. The underlying wallet class here is what the O3 wallet uses. You can open any other relevant issues, but I would **strongly** recommend you read the contributing guidelines before continuing to do so.

**Comment by WyattMufson** [comment]
Clarification: the `Wallet` class is the equivalent of an Ontology account

If you are worried about storage you can either:
- Store just the encrypted key (and then rebuild the `Wallet` object when you want to access it)
- Create a [codable](https://developer.apple.com/documentation/swift/codable) wallet object with an account and identities array.

**Comment by WyattMufson** [comment]
`neovmUtils` uses just "Accounts" but refer to them as `Wallet`. It's simpler and makes more sense for the average user.

**Comment by lrmz** [comment]
Ontology wallet needs to be bound to an account to manage assets. I think you also need to provide a method for related functions.

**Comment by WyattMufson** [comment]
@lrmz refer to my previous comment. The community is welcome to add an `OntologyWallet` class if they want to manage a list of `Wallet` objects. Developers won't really use that since it's unnecessary and not really documented anywhere. This current solution actually works quite well and has far more users.

**Comment by WyattMufson** [comment]
Opened #15 for creation of `OntologyWallet` class

**Comment by WyattMufson** [comment]
@lrmz for reference, the [OntologyWallet class](https://github.com/Ryucoin/neovm-utils/blob/master/docs/ont-wallet.md) has been added. You can add `Account` objects (same as `Wallet`) and `Identity` objects. The encrypted key stuff has been built into the `Account`/`Wallet` class and can be accessed with the `lock` and `unlock` methods, [as seen in the documentation](https://github.com/Ryucoin/neovm-utils/blob/master/docs/wallet.md#lock).
