### ISSUE TITLE
Ontology Transactions

### ISSUE THREAD

**Issue by lrmz** [Ryucoin/neovm-utils#16]
How do I choose ONT/ONG and the number of transfers when I construct a transaction?

**Comment by WyattMufson** [comment]
You need to specify more details when [asking a question](https://stackoverflow.com/help/how-to-ask).

**Comment by WyattMufson** [comment]
You can make a transfer with https://github.com/Ryucoin/neovm-utils/blob/master/neovmUtils/Classes/OntologyRPC.swift#L147

The current transaction building is for invoking a neovm smart contract. Besides the transfer function the only nativevm invocation is done in DID.

**Comment by lrmz** [comment]
When I am using neovmUtils, I refer to ONT Transactions and then use buildOntologyInvocationTransaction() to construct a transaction.
How do I choose ONT/ONG and the number of transfers when I construct a transaction?

**Comment by WyattMufson** [comment]
`buildOntologyInvocationTransaction` builds a transaction for a neovm smart contract, not native contracts. For transfer you have to use `ontologyTransfer`

**Comment by lrmz** [comment]
ok
